/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame2.java
 *
 * Created on May 11, 2013, 2:57:50 PM
 */

package mary;
import java.awt.Robot;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.*;
import java.lang.*;
import java.io.*;
import java.util.HashSet;
import java.util.Set;
import javax.swing.ComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author welcome-raj
 */

public class Flight extends javax.swing.JFrame {
    /** Creates new form NewJFrame2 */
    public Flight() {
        initComponents();
    // String[] str= new String[1];
      //  Flight.main(str);
       
    }
    static voice obj=new voice();
    int count=0;
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight_ID", "Source", "Destination", "Departure Time","Arrival Time", "Price", "Availability","Date"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("APPLICATION :");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("ADMINISTRATOR :");

        /*
        jTextField2.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTextField2InputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        */

        jLabel3.setText("Flight Details");

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 815, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(39, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                        .addGap(85, 85, 85))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
try {
    
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/MakeMyTrip","root","tiger");
       Statement st= con.createStatement();
      Statement st1=con.createStatement();
      fid=jTextField2.getText();
       String str= "delete from flight where flight_id= '"+fid+"'";
       String str1="delete from flight_avail where flight_id= '"+fid+"'";
       System.out.print(str);
        st.executeUpdate(str);
        st1.executeUpdate(str1);
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
       
        while(model.getRowCount()>0)
        {
            model.removeRow(0);
       // System.out.print("hello");
        }
       String[] string=new String[1];
        main(string);
}catch(Exception e){}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String source=new String();
         String dest=new String();
        String atime=new String();
          String dtime=new String();
        String price=new String();
        String avail=new String();
        String date=new String();
         voice obj=new voice();
String string=new String();
            string="Enter the Flight ID";
          jTextField1.setText(string);
           obj.dospeak(string,"kevin");
           wait(string);
           fid = answer;
           jTextField2.setText("");
           
            string="Enter the source";
          jTextField1.setText(string);
           obj.dospeak(string,"kevin");
           wait(string);
           source = answer;
jTextField2.setText("");
           
           string="Enter the Destination";
          jTextField1.setText(string);
           obj.dospeak(string,"kevin");
           wait(string);
           dest = answer;
jTextField2.setText("");
           
           string="Enter the Arrival time";
          jTextField1.setText(string);
           obj.dospeak(string,"kevin");
           wait(string);
           atime = answer;
jTextField2.setText("");
           
           string="Enter the Departure time";
          jTextField1.setText(string);
           obj.dospeak(string,"kevin");
           wait(string);
           dtime = answer;
jTextField2.setText("");
           
           string="Enter the price";
          jTextField1.setText(string);
           obj.dospeak(string,"kevin");
           wait(string);
           price = answer;
           jTextField2.setText("");
           
           string="Enter the date";
          jTextField1.setText(string);
           obj.dospeak(string,"kevin");
           wait(string);
           date = answer;
           String split[] = date.split("-");
           date= split[2]+"-"+split[1]+"-"+split[0];
           
           jTextField2.setText("");
           
           string="Enter the Availibility";
          jTextField1.setText(string);
           obj.dospeak(string,"kevin");
           wait(string);
           avail = answer;
jTextField2.setText("");
           
           try {
              
           Class.forName("com.mysql.jdbc.Driver");
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/MakeMyTrip","root","tiger");
           Statement st= con.createStatement();
           Statement st1= con.createStatement();
           String str= "insert into flight values('"+fid+"','"+source+"','"+dest+"','"+atime+"','"+dtime+"','"+price+"')";
           String str1= "insert into flight_avail values('"+fid+"','"+date+"','"+avail+"')";
            st.executeUpdate(str1); 
           st.executeUpdate(str); 
            System.out.print(str);
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
       
              while(model.getRowCount()>0)
            {
            model.removeRow(0);
            }
       String[] string1=new String[1];
        main(string1);
       }catch(Exception e){
       e.printStackTrace();}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
/*
    private void jTextField2InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextField2InputMethodTextChanged
        // TODO add your handling code here:
        String string=new String();
         String str=new String();
        string=jTextField2.getText();
        if(string.contains("delete"))
               {
                    str="please give flight id";    
                   obj.dospeak(str,"kevin");
                    jTextField1.setText("");
               //     wait(string);
                    fid = answer;
                    jButton2.doClick();
                    
                    
               }else if(string.contains("add"))
               {
                   jButton1.doClick();
               }
    }//GEN-LAST:event_jTextField2InputMethodTextChanged
*/
    static String fid = new String();

    /**
    * @param args the command line arguments
    */

    static String  answer=new String();
    
    
    public static void main(String args[]) {
       
        //new Flight().setVisible(true);
        System.out.println(Thread.activeCount());
//          jTextField1.setText(ss[2]);
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/MakeMyTrip","root","tiger");
       Statement st= con.createStatement();
      
      String str= "select * from flight,flight_avail where flight.FLIGHT_ID=flight_avail.FLIGHT_ID";
       System.out.print(str);
       ResultSet rs = st.executeQuery(str);
          while(rs.next()){
          System.out.print(rs.getString(1));
          System.out.print(rs.getString(2));
          System.out.print(rs.getString(3));
          System.out.print(rs.getString(4));
          System.out.print(rs.getString(5));
          System.out.println();
          DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
          model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(8),rs.getString(9)});
         
          }
          
        
      //    String f_id = new String();
          
       // Robot rb=new Robot();
           String string=new String();
      //     String str=new String();

    jTextField1.setText("");
          str="What you want to do admin?";
          jTextField1.setText(str);
        obj.dospeak(str,"kevin");
        wait(string);
          string = answer;
          jTextField2.setText("");
       while(true)
       {
           if(string.contains("delete"))
               {
                    str="please give flight id";    
                    obj.dospeak(str,"kevin");
                    jTextField1.setText("");
                    wait(string);
                    fid = answer;
                    jButton2.doClick();
                    
                    
               }if(string.contains("add"))
               {
                   jButton1.doClick();
               }
               if(string.contains("back"))
               {
                   new Admin().setVisible(true);
                   String[] s=new String[1];
                   Admin.main(s);
               }   
               
       string=jTextField2.getText();     
       }
          } catch (SQLException e) {
            System.out.println("SQL Exception: "+ e.toString());
        } catch (ClassNotFoundException cE) {
            System.out.println("Class Not Found Exception: "+ cE.toString());
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
       //      new Flight().setVisible(true); 
         
            }
            
        });
           jTextField1.setText("hello");
    }
    
public static void wait(String str){
        String str1;
     System.out.println("welcome");
    sleep();
    try{
        str1=jTextField2.getText();
  //  while(true){
        
    while(jTextField2.getText().isEmpty())
    {    
        sleep();
    }
    answer=jTextField2.getText();
           
    }catch(Exception e){}
   // }
}
    public static void sleep(){
    try{
        String str;
    Robot rb=new Robot();
     //                 jTextField2.setText(str);
//             obj.dospeak(str,"kevin");
                rb.keyPress(KeyEvent.VK_CONTROL);
            rb.keyPress(KeyEvent.VK_1);
            rb.keyRelease(KeyEvent.VK_CONTROL);
            rb.keyRelease(KeyEvent.VK_1);
             Thread.sleep(2000);
              str=jTextField2.getText();
              Thread.sleep(2000);
              System.out.println("hello");
              while(! jTextField2.getText().equals(str))
              {
                    str=jTextField2.getText();
                  Thread.sleep(2000);
              }
             rb.keyPress(KeyEvent.VK_CONTROL);
            rb.keyPress(KeyEvent.VK_1);
            rb.keyRelease(KeyEvent.VK_CONTROL);
            rb.keyRelease(KeyEvent.VK_1);

    }catch(Exception e){}
    
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton jButton1;
    private static javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jTable1;
    private static javax.swing.JTextField jTextField1;
    private static javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

}
