/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame4.java
 *
 * Created on Jul 9, 2013, 9:07:05 AM
 */

package mary;

import java.awt.AWTException;
import java.awt.Robot;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author welcome-raj
 */
public class NewJFrame4_1 extends javax.swing.JFrame {
static String answer,date;
    /** Creates new form NewJFrame4 */
    public NewJFrame4_1() {
        initComponents();
    }
static int avail=-1;
public static String strin = new String();
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(8, 8, 64));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 255), 8, true));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mary/9.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("SOURCE :");

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 0, 102));
        jTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 255), 3, true));
        jTextField1.setFocusable(false);
        jTextField1.setRequestFocusEnabled(false);

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("DESTINATION :");

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(0, 0, 102));
        jTextField2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 255), 3, true));
        jTextField2.setFocusable(false);
        jTextField2.setRequestFocusEnabled(false);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(0, 0, 102));
        jButton1.setText("SUBMIT");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 255), 2, true));
        jButton1.setFocusable(false);
        jButton1.setRequestFocusEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setForeground(new java.awt.Color(0, 0, 102));
        jButton2.setText("LOGOUT");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 255), 2, true));
        jButton2.setFocusable(false);
        jButton2.setRequestFocusEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setForeground(new java.awt.Color(0, 0, 102));
        jButton3.setText("MAP");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 255), 2, true));
        jButton3.setFocusable(false);
        jButton3.setRequestFocusEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)))
                .addGap(39, 39, 39)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 255), 8, true));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mary/mic.gif"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 102));
        jLabel9.setText("MAKE MY TRIP ++");

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(0, 0, 102));
        jTextField3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 255), 3, true));
        jTextField3.setFocusable(false);
        jTextField3.setRequestFocusEnabled(false);

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 102));
        jLabel10.setText("GUEST");

        jTextField4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(0, 0, 102));
        jTextField4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 255), 3, true));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField4)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField3)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight_ID", "Source", "Destination", "Departure Time","Arrival Time", "Price", "Availability","Date"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Date" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 885, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(189, 189, 189))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mary/5.jpg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 80)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("MAKE MY TRIP++");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mary/5.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("We know where you are going..... We would love to plan your trip..... ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel4))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  //new NewJFrame5().setVisible(true);
  //NewJFrame5.main(uname);
        System.out.println(avail);
        if(avail!=-1)
        {
            
            avail--;
            try {
                Class.forName("com.mysql.jdbc.Driver");
            
                      Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/test","root","tiger");
                   // Statement st=con.createStatement();
                      String sql="update flight_avail set Availibility =? where Flight_ID =? and Date =?";
                      PreparedStatement st = con.prepareStatement(sql);
                      st.setInt(1,avail);
                      st.setString(2,fid);
st.setString(3,String.valueOf(jComboBox1.getSelectedItem()));
                      //  int f_id=Integer.parseInt(fid);
                 //   System.out.println("update flight set Availibility ='"+avail+"' where Flight_ID = '"+f_id+"'");
               st.executeUpdate();
                      //st.executeUpdate("update table flight set Availibility ='"+avail+"' where Flight_ID = '"+f_id+"'");
            String[] str=new String[5];
               str[0]=fid;
            str[1]=uname[0];
            str[2]=uname[1];
            str[3]=time;
            str[4]=date;
               this.setVisible(false);
            new NewJFrame2().setVisible(true);
            NewJFrame2.main(str);
            } catch (Exception ex) {
                ex.printStackTrace();
            }
            }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this.setVisible(false);
 new NewJFrame().setVisible(true);
 String[] str=new String[2];
 NewJFrame.main(str);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

           Process p;
try {
    String command = "rundll32 url.dll,FileProtocolHandler \""+ "C:/Users/dell/Desktop/Mary/src/mary/Map/map.jpg" +"\"";

    p = Runtime.getRuntime().exec(command);
    p.waitFor();

} catch (Exception e) {
    // TODO Auto-generated catch block
e.printStackTrace();
}
 jTextField4.setText("");
 
 // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
static int j=0;
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
     j=1;   // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    /**
    * @param args the command line arguments
    */
   
    public static String[] uname = new String[2]; 
        public static String dest,source,fid,time;
    /**
     *
     * @param args
     * @throws AWTException
     * @throws InterruptedException
     */
  public static text tx=new text();
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
       new NewJFrame4_1().setVisible(true);     
                
                 // NewJFrame().setVisible(false);
            }
        });
   time=args[2];
        try{
            //Keep in ON state initially
            //OFF

            
                    voice obj=new voice();
                    String string;                    
                  //  jLabel8.setText(args[0]);
             String str="Welcome back !!! "+args[0];//+args[0];
             obj.dospeak(str,"kevin16");
             tx.text1(str, time);
             jTextField3.setText(str);

             str="Tell me about your trip";
             obj.dospeak(str,"kevin16");
             tx.text1(str, time);
             jTextField3.setText(str);
                    //
             String day= new String();
             String month= new String();
            
            int i=0;
            while(i<1)
            {
                retrip();
                while(answer.contains("Map"))
                retrip();
                jTextField4.setText("");
               
             
             
                Class.forName("com.mysql.jdbc.Driver");
               
                      Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/test","root","tiger");
                    Statement st=con.createStatement();
                   
                      String strin= "select * from flight,flight_avail where flight.FLIGHT_ID=flight_avail.FLIGHT_ID and Source='"+source+"' and destination='"+dest+"' and Date - CURDATE()<=7 and Date - CURDATE()>0" ;
       System.out.print(strin);
       ResultSet rs = st.executeQuery(strin);
          while(rs.next()){
          System.out.print(rs.getString(1));
          System.out.print(rs.getString(2));
          System.out.print(rs.getString(3));
          System.out.print(rs.getString(4));
          System.out.print(rs.getString(5));
          System.out.println();
          DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
          model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(9),rs.getString(8)});
          jComboBox1.addItem(rs.getString(8));
          //jComboBox2.addItem(rs.getString(8));
         i++;
          }
          
           
                str="Select the date";
             obj.dospeak(str,"kevin16");
             tx.text1(str, time);
             jTextField3.setText(str);
          while(String.valueOf(jComboBox1.getSelectedItem()).contains("Date")){
          System.out.println("hello world"+jComboBox1.getSelectedItem());
          }
              
          uname[0]=args[1];
                    uname[1]=args[0];

            
               //   ResultSet rs=st.executeQuery("Select FLIGHT_ID,Availibility  from flight where Source='"+source+"'and destination ='"+dest+"'");
            
            if(i>0)
            {

                str="Enter the flight ID";
                obj.dospeak(str,"kevin");
                jTextField3.setText(str);
                tx.text1(str, time);
                    jTextField4.setText("");
                 while((jTextField4.getText().trim()).isEmpty())
                 {
                     System.out.print("");
                 }
                 
                fid=jTextField4.getText();
                tx.text1(fid, time);
                  jTextField4.setText("");   
                Class.forName("com.mysql.jdbc.Driver");
                      Connection con2 = DriverManager.getConnection("jdbc:mysql://localhost:3306/test","root","tiger");
                    Statement st1=con2.createStatement();
                    date=String.valueOf(jComboBox1.getSelectedItem());
                      String strin1= "select availibility from flight_avail where flight_avail.FLIGHT_ID='"+fid+"' and date ='"+jComboBox1.getSelectedItem()+"'" ;
       System.out.print(strin);
       ResultSet rs1 = st1.executeQuery(strin1);
                
        if(rs1.next())
            {i++;
            avail=rs1.getInt(1);
            }
        else
            { 
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("Not a valid Flight Id");
                tx.text1("Not a valid Flight Id", time);
                obj.dospeak(" Not a valid Flight Id", "kevin16");
                
            }
                //obj.dospeak("Please Press The Submit Button to confirm", "kevin16");
                  //  jTextField.setText("Please Press The Submit Button to confirm");
            }
            else
            { 
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("Not a valid source or destination");
                tx.text1("Not a valid source or destination", time);
                obj.dospeak(" Not a valid source or destination", "kevin16");
                
            }
            }


            
            if(avail>0)
            str=String.valueOf(avail)+" Tickets available for your trip!";
             else{
                 str="Sorry !"+uname[0]+" ,No tickets are available on this date";
                 
             }
            obj.dospeak(str,"kevin16");
            jTextField3.setText(str);
             tx.text1(str, time);
            
            
            str="Submit ,"+uname[0]+" !! to enter deatils";
            obj.dospeak(str,"kevin16");
            tx.text1(str, time);
           // jTextField3.setText(str);
            
            while(true)
            {
                sleep();
             //   System.out.print("Hi");
                 string=jTextField4.getText();
                 tx.text1(string, time);
                   //string=string.trim();
               if(string.contains("Submit")||string.contains("submit"))
             {
                 jButton1.doClick();
             }else if(string.contains("Logout")||string.contains("Sign out"))
             {
              jButton2.doClick();
                 
             }else if(string.contains("Map")){
             jButton3.doClick();
             }
            }
         
            }
    
catch(Exception e){
e.printStackTrace();
}

    }
    public static void wait(String str){
    
//   if(str.length()<1)
  //      str="Sir";
    try{
 
    while(!(jTextField4.getText().contains("from"))||!(jTextField4.getText().contains("to")))
    {
       
        voice obj=new voice();
        obj.dospeak( str+", please give correct information","kevin");
        jTextField3.setText("please give correct information");
        tx.text1("please give correct information",time);
        jTextField4.setText("");
        sleep();
        
    }
    }catch(Exception e){}
    
    }
    public static void wait1(String str){
        String str1;
     //   int i=0;
    sleep();
    if(str.length()<1)
        str="Sir";
    
    try{
        str1=jTextField3.getText();
  //  while(true){
        
    while(jTextField3.getText().isEmpty())
    {    
        sleep();
    }
    answer=jTextField3.getText();
           
    }catch(Exception e){}
    
    }
     
    public static void sleep(){
    try{
        String str;
    Robot rb=new Robot();
     //                 jTextField2.setText(str);
//             obj.dospeak(str,"kevin");
                rb.keyPress(KeyEvent.VK_CONTROL);
            rb.keyPress(KeyEvent.VK_1);
            rb.keyRelease(KeyEvent.VK_CONTROL);
            rb.keyRelease(KeyEvent.VK_1);
             Thread.sleep(2000);
              str=jTextField4.getText();
              Thread.sleep(2000);
              while(! jTextField4.getText().equals(str))
              {
                  str=jTextField4.getText();
                  Thread.sleep(2000);
              }
             rb.keyPress(KeyEvent.VK_CONTROL);
            rb.keyPress(KeyEvent.VK_1);
            rb.keyRelease(KeyEvent.VK_CONTROL);
            rb.keyRelease(KeyEvent.VK_1);
            answer=str;

    }catch(Exception e){}
}
    
    public static void retrip()
    {
        try{
             String string= new String();
             while(jTextField4.getText().isEmpty())
            sleep();
             string=jTextField4.getText();
             tx.text1(string, time);
             
             if(string.contains("Map"))
             {
                 jButton3.doClick();
             }
             else
             {
             wait(string);
             string=jTextField4.getText();
             //tx.text1(string, time);
             
               if(string.length()>10)
               {
                    String[] split = string.split("from");
                split[1] = split[1].trim();
                    split=split[1].split(" ",2);
                     source=split[0];
                     String[] split1 = string.split("to");
               split1[1] = split1[1].trim();
                     split1=split1[1].split(" ",2);
                     dest=split1[0];
                    System.out.println("Source "+source+"  destination: "+dest);
                    jTextField1.setText(source);
                    jTextField2.setText(dest);
               }
             }
           }

               catch(Exception e)
               {
               }}
      
            
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton jButton1;
    private static javax.swing.JButton jButton2;
    private static javax.swing.JButton jButton3;
    private static javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private static javax.swing.JTable jTable2;
    private static javax.swing.JTextField jTextField1;
    private static javax.swing.JTextField jTextField2;
    private static javax.swing.JTextField jTextField3;
    private static javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

}
