package mary;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on Jul 11, 2013, 6:32:18 PM
 */
import java.util.*;
import com.sun.speech.freetts.*;
import java.awt.Robot;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

//import java.beans.Statement;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.net.UnknownHostException;

//import java.sql.Connection;
//import java.sql.DriverManager;
import java.awt.event.KeyEvent;
//import java.sql.Connection;
//import java.sql.DriverManager;
//import java.sql.ResultSet;
//import java.sql.SQLException;


//import java.sql.Statement;
//import javax.sound.sampled.AudioInputStream;
//import javax.sound.sampled.AudioSystem;
//import javax.sound.sampled.LineEvent;
//import javax.sound.sampled.LineListener;
//import javax.sound.sampled.UnsupportedAudioFileException;
//import marytts.client.MaryClient;
//import marytts.util.data.audio.AudioPlayer;
//import marytts.client.http.Address;

//import java.sql.Connection;
//import java.sql.DriverManager;

import java.io.*;
import java.sql.Timestamp;
//import java.nio.charset.Charset;
//import mary.voice;
/**
 *
 *
 *
 * @author welcome-raj
 */
public class NewJFrame extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    public NewJFrame() {
        initComponents();
    }
    static String[] ss=new String[4];
    public static String serverHost= new String();
    public static int serverPort=0,choice=-1,timer=0;
// public static MaryClient mary;
 public static String name=new String();
    public static String answer=new String();
    public static String username=new String();
    public static String pass=new String();
    public static String check_pass=new String();
   public static String nick;

/*
    public static void speak(String str)
    {
        try
        {
        
        
        String text = str;
        String locale = "en-US"; // or US English (en-US), Telugu (te), Turkish (tr), ...
        String inputType = "TEXT";
        String outputType = "AUDIO";
        String audioType = "WAVE";
        String defaultVoiceName = null;
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        mary.process(text, inputType, outputType, locale, audioType, defaultVoiceName, baos);
        // The byte array constitutes a full wave file, including the headers.
        // And now, play the audio data:
        AudioInputStream ais = AudioSystem.getAudioInputStream(
            new ByteArrayInputStream(baos.toByteArray()));
         LineListener lineListener = new LineListener() {

            public void update(LineEvent event) {
                throw new UnsupportedOperationException("Not supported yet.");
        //    }
         }
        };

        //};

        AudioPlayer ap = new AudioPlayer(ais, lineListener);
        ap.start();
    }

            catch(Exception e){}
        } ;
*/
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        canvas1 = new java.awt.Canvas();
        canvas2 = new java.awt.Canvas();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 32700));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 129, 19), 8, true));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 0));
        jLabel2.setText("USERNAME");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mary/1.jpg"))); // NOI18N

        jPasswordField1.setEditable(false);
        jPasswordField1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(0, 51, 0));
        jPasswordField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 3, true));
        jPasswordField1.setFocusable(false);
        jPasswordField1.setRequestFocusEnabled(false);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 0));
        jLabel4.setText("PASSWORD");

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 51, 0));
        jTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 3, true));
        jTextField1.setFocusable(false);
        jTextField1.setRequestFocusEnabled(false);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 51, 0));
        jButton3.setText("LOGIN");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 0), 3, true));
        jButton3.setFocusable(false);
        jButton3.setRequestFocusEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(83, 83, 83)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3))
                        .addGap(13, 13, 13)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 129, 19), 8, true));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 0));
        jLabel5.setText("MAKE MY TRIP++");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mary/mic.gif"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 0));
        jLabel7.setText("GUEST");

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(0, 51, 0));
        jTextField2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 3, true));
        jTextField2.setFocusable(false);
        jTextField2.setRequestFocusEnabled(false);

        jTextField3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(0, 51, 0));
        jTextField3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 254), 3, true));
        /*
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        */

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jTextField2)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                    .addComponent(jTextField3))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mary/travel5.jpg"))); // NOI18N

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 129, 19), 8, true));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mary/pilot_flying_plane.gif"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mary/travel 10.jpg"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mary/travel11.jpg"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mary/travel13.jpg"))); // NOI18N

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ABOUT");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 0), 1, true));
        jButton1.setFocusable(false);
        jButton1.setRequestFocusEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setForeground(new java.awt.Color(0, 51, 0));
        jButton2.setText("SERVICES");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 0), 1, true));
        jButton2.setFocusable(false);
        jButton2.setRequestFocusEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(67, 67, 67)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(416, 416, 416)
                                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(canvas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(341, 341, 341)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(130, 130, 130))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(canvas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(136, 178, 27));

        jLabel1.setFont(new java.awt.Font("Goudy Old Style", 1, 80)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MAKE MY TRIP++");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mary/5.jpg"))); // NOI18N

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mary/5.jpg"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 51, 0));
        jLabel15.setText("We know where you are going .... We would love to plan your trip....");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)))
                .addComponent(jLabel14)
                .addGap(84, 84, 84))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel14)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel15))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Process p;
try {
    String command = "rundll32 url.dll,FileProtocolHandler \""+ "D:\\Master's Research\\Lusip\\Mary\\src\\mary\\About\\ABOUT.jpg" +"\"";

    p = Runtime.getRuntime().exec(command);
    p.waitFor();

} catch (IOException e) {
    // TODO Auto-generated catch block

} catch (InterruptedException e) {
    
}
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.out.println("hello welcome to button");
                  Process p;
try {
    String command = "rundll32 url.dll,FileProtocolHandler \""+ "D:\\Master's Research\\Lusip\\Mary\\src\\mary\\Service\\service.jpg" +"\"";

    p = Runtime.getRuntime().exec(command);
    p.waitFor();

} catch (Exception e) {
    // TODO Auto-generated catch block
e.printStackTrace();
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(!jTextField1.getText().isEmpty()&&!jPasswordField1.getText().isEmpty())
        {  ss[0]=nick;
        ss[1]=username;
        ss[2]=time;
        this.setVisible(false);
        new NewJFrame4_1().setVisible(true); 
       NewJFrame4_1.main(ss);
        }  // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
    * @param args the command line arguments
    */
  public  final static SoundRecordingUtil recorder = new SoundRecordingUtil();
  
  public SoundRecordingUtil get()
  {
     return recorder; 
  }
    static String  time= new String();
    
    
    public static void main(String args[]) {
          java.util.Date date= new java.util.Date();
	time=String.valueOf(new Timestamp(date.getTime()));
         String[] split= time.split(" ");
        time=split[1];
        System.out.print(time);
        String[] split1= time.split(":");
        time=split1[0]+split1[1]+split1[2];
        System.out.print(time);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
                
            }
        });
        try{
        //serverHost = System.getProperty("server.host", "cling.dfki.uni-sb.de");
       // serverPort = Integer.getInteger("server.port", 59125).intValue();
      // mary = MaryClient.getMaryClient(new Address(serverHost, serverPort));

       voice obj=new voice();
       text tx=new text();
        
       TestSoundRecordingUtil tsru= new TestSoundRecordingUtil();
        //final SoundRecordingUtil recorder = new SoundRecordingUtil();
        //ss[3]=String.valueOf(recorder);
        tsru.record(0,recorder,time);
      // Robot rb=new Robot();
             String string=new String();
            String str="Welcome User!";
            obj.dospeak(str,"kevin");
            tx.text1(str, time);
              jTextField2.setText(str);
             //Thread.sleep(500);
              str="This is MAKE MY TRIP++!";
             obj.dospeak(str,"kevin");
             tx.text1(str, time);
              jTextField2.setText(str);
              ///Thread.sleep(500);
              
             str="Please tell me your name?";
               obj.dospeak(str,"kevin");
               tx.text1(str, time);
              jTextField2.setText(str);
             // Thread.sleep(500);
             wait(string);
             string= answer;
             tx.text1(answer, time);
            getName(string);//////
            string=name;
            if(!string.contains("skip"))
            nick=string;
            else
                nick="friend";
            //jLabel8.setText(string);
              jTextField3.setText("");

            //  str="Hi!!"+str;
            //  jTextField2.setText(str);
            if(!string.contains("skip"))
           {
              obj.dospeak("Hi, "+string +" ! How are you feeling today?","kevin");
              jTextField2.setText("How are you feeling today?");
              tx.text1("How are you feeling today?", time);
              //Thread.sleep(500);
               wait(str);
               string=answer;
              tx.text1(answer, time);
               if(string.contains("fine")||string.contains("good"))
               {
                    str="Ohh! That's great!!";    
                    obj.dospeak(str,"kevin");
                    tx.text1("str", time);
                    jTextField3.setText("");
               }
                else if(string.contains("not")||string.contains("Bad")||string.contains("upset")||string.contains("angry")||string.contains("Sad"))
               {
                   jTextField3.setText("");
                   str="Why Buddy,What happened!!";
                    jTextField2.setText(str);
                   obj.dospeak(str,"kevin");
                   tx.text1(str, time);
                   wait(str);
                   string=answer;
                   tx.text1(answer, time);
                   if(string.contains("Nothing")||string.isEmpty())
                   {
                      obj.dospeak("It's Okay!"+nick+" .Don't tell me the reason.My sympathy is with you.","kevin");
                   }
                   else
                   {
                      obj.dospeak("Oh! That's so sad "+nick,"kevin");
                   }
                   jTextField3.setText("");
                   str=" I will soon cheer you up "+nick+" !";
                      tx.text1(str, time);

                    jTextField2.setText(str);
                   obj.dospeak(str,"kevin");                    
                }
           }    
              str="How can I help you "+nick+"!";
              obj.dospeak(str,"kevin");
               tx.text1(str, time);
              jTextField2.setText(str);
             // tsru.record(1,recorder,time);
              while(true)
              {  
                 wait(string);
                 string=answer;
                 tx.text1(answer, time);
                 if(string.contains("New")||string.contains("Sign up")||string.contains("Register"))
                {
                    jTextField2.setText("Creating a new user profile!!");
                                         choice=0;
                    obj.dospeak("Creating a new user profile!!","kevin");
                    tx.text1("Creating a new user profile!!", time);
                    jTextField3.setText("");
                    enter(string);
                    jTextField2.setText("How can I help you "+nick+"!");
                    tx.text1("How can I help you ", time);
                }
                else if(string.contains("Sign in")||string.contains("Login"))
                {
                    jTextField2.setText("Starting process for login");
                    choice=1;
                    obj.dospeak("Starting process for login","kevin");
                    tx.text1("Starting process for login", time);
                    jTextField3.setText("");
                    enter(string);
                }
                 else if(string.contains("About")){
                    //press submit    
                    jButton1.doClick();                    
                    obj.dospeak("This software,is developed by Sweety Ramnani under the guidance of Professor Ravi Prakash Gorthi...","kevin");
                    tx.text1("This software,is developed by Sweety Ramnani the guidance of Professor Ravi Prakash Gorthi...", time);
                    //obj.dospeak("Like us on facebook or follow us on twitter with the name crazytechs...","kevin");
                    jTextField2.setText("How can I help you "+nick+"!");
                     tx.text1("How can I help you ", time);
                    jTextField3.setText("");
                }
                else if(string.contains("Service")){
                jButton2.doClick();
                obj.dospeak("Apart from Airline Reservation, we also provide online cab booking and online hotel booking","kevin");
                tx.text1("Apart from Airline Reservation, we also provide online cab booking and online hotel booking", time);
                jTextField2.setText("How can I help you "+nick+"!");
                tx.text1("How can I help you ", time);
                jTextField3.setText("");
                }
              
              }

        }catch(Exception e){}

        }

     public static void getName(String str){
 //  str=str.trim();
    if(str.contains("is")){
        String[] split= str.split("is");
        if(split[0].contains("name")||split[0].contains("Name")||split[0].contains("password")||split[0].contains("Password")||split[0].contains("username"))
        name=split[1];
        else
            name=split[0];
    }
    else if(str.length()>=3){
            name=str;
            name = name.trim();
    }

}
    public static void wait(String str){
        String str1;
     //   int i=0;
    sleep();
    if(str.length()<1)
        str="Sir";
    else
        str=nick;
    try{
        str1=jTextField3.getText();
  //  while(true){
        
    while(jTextField3.getText().isEmpty())
    {    
        sleep();
    }
    answer=jTextField3.getText();
           
    }catch(Exception e){}
   // }
}
    public static void sleep(){
    try{
        String str;
    Robot rb=new Robot();
     //                 jTextField2.setText(str);
//             obj.dospeak(str,"kevin");
                rb.keyPress(KeyEvent.VK_CONTROL);
            rb.keyPress(KeyEvent.VK_1);
            rb.keyRelease(KeyEvent.VK_CONTROL);
            rb.keyRelease(KeyEvent.VK_1);
             Thread.sleep(2000);
              str=jTextField3.getText();
              Thread.sleep(2000);
              while(! jTextField3.getText().equals(str))
              {
                  str=jTextField3.getText();
                  Thread.sleep(2000);
              }
             rb.keyPress(KeyEvent.VK_CONTROL);
            rb.keyPress(KeyEvent.VK_1);
            rb.keyRelease(KeyEvent.VK_CONTROL);
            rb.keyRelease(KeyEvent.VK_1);

    }catch(Exception e){}
}
    public static void check(){
        try{
            //System.out.println("hi hello bye..");
        Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/test","root","tiger");
            Statement st=(Statement) con.createStatement();
            ResultSet rs=st.executeQuery("Select * from record where username ='"+username+"'"); 
           
            
            while(rs.next())
            {
                
                if(rs.getString(1).equals(username))
                {
                    check_pass=rs.getString(2);
                    System.out.println(check_pass);
                }
            }
            con.close();
        }catch(Exception e){
        e.printStackTrace();
        }

    }
    public static void func(){
      try{
         Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/test","root","tiger");
            Statement st=(Statement) con.createStatement();
            System.out.println("insert into record values ('"+username+"','"+pass+"')");
           st.executeUpdate("insert into record values ('"+username+"','"+pass+"')");
           con.close(); 
        }catch(Exception e){
        e.printStackTrace();
        }

}
public static void enter(String string){
    text tx= new text();           
    voice obj=new voice();
              String str="Please tell me your user name!";
              tx.text1("Please tell me your user name!", time); 
              jTextField2.setText(str);
                 obj.dospeak(str,"kevin");/////
                 wait(string);
                string= answer;/////
               tx.text1(answer, time); 
               getName(string);
                  string=name;
               username=name;
               username=username.trim();
             jTextField3.setText("");


                 str="Please tell me your password!";
                 jTextField2.setText(str);
                 tx.text1("Please tell me your password!", time);
                  obj.dospeak(str,"kevin");
               wait(string);
               string= answer;
                tx.text1(answer, time);
                getName(string);//////
               string=name;
               pass=name;
               pass=pass.trim();
                System.out.println("insert into record values ('"+username+"','"+pass+"')");
                 
                jTextField3.setText("");
                 jTextField2.setText("");
            // obj.dospeak(str,"kevin");

           // int choice =0;
             if(choice==0)///new user
               {
                // obj.dospeak("welcome to check","kevin");
                   check();

                   if(check_pass.isEmpty())
                   {
                       System.out.println("Value of check is"+check_pass);
                
                       // jTextField2.setText("Welcome ");
         //          Thread.sleep(1000);
                       jTextField2.setText("Welcome !!"+username+"You have successfully registered...");
                        tx.text1("Welcome !!"+username+"You have successfully registered...", time);
                       //  choice=3;
                         obj.dospeak("Welcome !!"+username+"You have successfully registered...","kevin");
                         
                         func();//save its details in database
                   
                   }
                   else
                   {
                     
                         jTextField2.setText("Sorry Sir!!! The Username You Have Entered is already in use..");
                         //choice=-1;
                        
                         obj.dospeak("Sorry!! "+nick+", The Username You Have Entered is already in use..","kevin");
                         tx.text1("Sorry!! "+nick+", The Username You Have Entered is already in use..", time);
                       
                         obj.dospeak("please try again with another name","kevin");
                        tx.text1("please try again with another name", time);
                       
                         enter(string);
                   }
               }
               else if(choice==1)//old user
               {
                   check();
                   if(check_pass.equals(pass))
                   {
                     jTextField1.setText(username);
                     jPasswordField1.setText(pass);
                     try{
                     Thread.sleep(1000);}catch(Exception e){}
                     jTextField2.setText("Login with username= "+ username +" and password= " + pass);
                     
                     if(username.equals("admin"))
                     {
                         new Admin().setVisible(true);
               Admin.main(ss);
                     }
                     else
                     jButton3.doClick();
               //  new NewJFrame().setVisible(false);
                     //  choice=3;
                   }
                   else
                   {
                       obj.dospeak("Username Password missmatch....","kevin");
                        tx.text1("Username Password missmatch....", time);
                       obj.dospeak("Please try again sir","kevin");
                       tx.text1("Please try again sir", time);
                       enter(str);
                   }

               }
}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Canvas canvas1;
    private java.awt.Canvas canvas2;
    private static javax.swing.JButton jButton1;
    private static javax.swing.JButton jButton2;
    private static javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private static javax.swing.JPasswordField jPasswordField1;
    private static javax.swing.JTextField jTextField1;
    private static javax.swing.JTextField jTextField2;
    private static javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

}
